# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-hermit-buildkite-plugin
  description: Buildkite Pipeline for hermit-buildkite-plugin
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/hermit-buildkite-plugin

spec:
  type: buildkite-pipeline
  owner: group:platform-dev-flow
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: hermit-buildkite-plugin
      description: 
    spec:
      repository: elastic/hermit-buildkite-plugin
      pipeline_file: ".buildkite/pipeline.yaml"
      teams:
        platform-dev-flow:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
