steps:
  - label: ":pre-commit: Pre-commit"
    command: pre-commit run --from-ref origin/HEAD --to-ref HEAD --show-diff-on-failure
    plugins:
      - elastic/hermit#v1.0.0
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
  - label: ":sparkles: Buildkite plugin Lint"
    command: lint --id elastic/hermit
    agents:
      image: buildkite/plugin-linter
