steps:
  - label: ":pre-commit: Pre-commit"
    command: pre-commit run --from-ref origin/HEAD --to-ref HEAD --show-diff-on-failure
    plugins:
      - elastic/hermit#v1.0.0
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential:latest@sha256:923bde2b5cced21dc9694119a5bd142789ba77146a0f813212c4cebd96971151"
  - label: ":sparkles: Buildkite plugin Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: elastic/hermit
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204
